[package]
name = "advent_of_code_2017"
version = "0.1.0"
authors = ["Olivier Pinon <opinon@asylum.fr>"]

[dependencies]
# WORKSPACES
day7_parser = { path = "day7_parser" }
day12_parser = { path = "day12_parser" }

# OTHER DEPS
petgraph = "*"
time = "*"
rayon = "*"

[workspace]
